# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180228_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(),
        ),
    ]
