# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-02 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180302_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=56),
        ),
    ]
